CREATE DATABASE IF NOT EXISTS to_do_list;

USE to_do_list;

CREATE TABLE users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(20) NOT NULL,
    Email VARCHAR(45) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES users(UserID)
        ON DELETE CASCADE
);